name: 'CI API'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - milo
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
      - name: Run Tests
          run: npm run test
